# -*- coding: utf-8 -*-
"""Dicionário PT->EN dos discriminadores únicos da Triagem de Manchester.

Traduções dos 186 discriminadores distintos da tabela oficial portuguesa,
usando a terminologia padrão do Manchester Triage System. A descrição
clínica (coluna H) fica só em português (é uma nota clínica isenta da
auditoria de traduções); aqui traduz-se apenas o texto curto da pergunta.
"""

DISCRIMINADORES_EN = {
    "Agressividade ou agitação moderada?": "Moderate aggression or agitation?",
    "Agressividade ou agitação severa?": "Severe aggression or agitation?",
    "Alarme automático?": "Automatic alarm?",
    "Alta de serviço de saúde mental nos últimos 15 dias?": "Discharge from a mental health service in the last 15 days?",
    "Alta mortalidade?": "High mortality?",
    "Alteração da coagulação?": "Coagulation disorder?",
    "Alteração da imunidade conhecida?": "Known immune impairment?",
    "Alteração da sensibilidade da face?": "Altered facial sensation?",
    "Alteração do estado de consciência?": "Altered level of consciousness?",
    "Alucinação aparente?": "Apparent hallucination?",
    "Angústia marcada?": "Marked distress?",
    "Apresentação de segmentos fetais?": "Presentation of fetal parts?",
    "Articulação quente?": "Hot joint?",
    "Asma sem melhoria com tratamento habitual?": "Asthma not improving with usual treatment?",
    "Auto-agressão sem antecedentes psiquiátricos?": "Self-harm without psychiatric history?",
    "Avulsão dentária recente?": "Recent tooth avulsion?",
    "Baba-se?": "Drooling?",
    "Bebé quente?": "Hot baby?",
    "Broncoespasmo?": "Bronchospasm?",
    "Cefaleia persistente?": "Persistent headache?",
    "Celulite escrotal?": "Scrotal cellulitis?",
    "Choro prolongado ou ininterrupto?": "Prolonged or incessant crying?",
    "Com Palpitações?": "Palpitations?",
    "Comportamento estranho na criança?": "Unusual behaviour in the child?",
    "Compromisso da via aérea?": "Airway compromise?",
    "Compromisso vascular distal?": "Distal vascular compromise?",
    "Confusão mental de novo?": "New-onset confusion?",
    "Convulsão atual?": "Current seizure?",
    "Corrimento?": "Discharge?",
    "Cólica?": "Colic?",
    "Deformação grosseira?": "Gross deformity?",
    "Deformação?": "Deformity?",
    "Diplopia?": "Diplopia (double vision)?",
    "Dispneia aguda?": "Acute shortness of breath?",
    "Disúria?": "Dysuria (pain passing urine)?",
    "Dor abdominal?": "Abdominal pain?",
    "Dor aórtica?": "Aortic pain?",
    "Dor moderada?": "Moderate pain?",
    "Dor persistente?": "Persistent pain?",
    "Dor pleurítica?": "Pleuritic pain?",
    "Dor precordial / VVC": "Precordial pain / coronary fast-track?",
    "Dor précordial?": "Precordial (central chest) pain?",
    "Dor que irradia para o ombro?": "Pain radiating to the shoulder?",
    "Dor severa?": "Severe pain?",
    "Dor testicular?": "Testicular pain?",
    "Dor à mobilização das articulações?": "Pain on moving the joints?",
    "Dor à palpação da região temporal?": "Tenderness over the temporal region?",
    "Défice neurológico agudo / VVAVC": "Acute neurological deficit / stroke fast-track?",
    "Défice neurológico agudo? <24h": "Acute neurological deficit? (<24h)",
    "Edema da face?": "Facial swelling?",
    "Edema da língua?": "Tongue swelling?",
    "Edema?": "Swelling?",
    "Eritema não branqueável?": "Non-blanching rash?",
    "Eritema persistente?": "Persistent redness?",
    "Eritema/rash persistente": "Persistent redness/rash?",
    "Erupção cutânea desconhecida?": "Unknown skin rash?",
    "Estridor?": "Stridor?",
    "Evisceração de orgãos?": "Organ evisceration?",
    "Exantema eritematoso ou bolhoso?": "Erythematous or blistering rash?",
    "Exaustão?": "Exhaustion?",
    "Falta de medicação c/ consequências graves e imediata?": "Missed medication with serious, immediate consequences?",
    "Febre persistente?": "Persistent fever?",
    "Fezes pretas ou raiadas de sangue?": "Black or blood-streaked stools?",
    "Fratura exposta?": "Open fracture?",
    "Gangrena escrotal?": "Scrotal gangrene?",
    "Grande Hemorragia incontrolável?": "Major uncontrollable haemorrhage?",
    "Hematemeses?": "Vomiting blood (haematemesis)?",
    "Hematoma do pavilhão auricular?": "Haematoma of the outer ear?",
    "Hematoma no couro cabeludo?": "Scalp haematoma?",
    "Hematoquésias, melenas ou retorragias?": "Blood in the stool or rectal bleeding?",
    "Hematúria clinicamente evidente?": "Clinically evident blood in the urine?",
    "Hemorragia catastrófica?": "Catastrophic haemorrhage?",
    "Hemorragia vaginal em gestação superior a 20 semanas?": "Vaginal bleeding in pregnancy over 20 weeks?",
    "Hemorragia vaginal intensa?": "Heavy vaginal bleeding?",
    "Hemorragia vaginal ligeira?": "Light vaginal bleeding?",
    "Hiperglicémia c/ cetose?": "Hyperglycaemia with ketosis?",
    "Hiperglicémia?": "Hyperglycaemia (high blood sugar)?",
    "Hipoglicémia?": "Hypoglycaemia (low blood sugar)?",
    "História Inapropriada?": "Inappropriate history?",
    "História cardíaca significativa?": "Significant cardiac history?",
    "História clinica significativa?": "Significant clinical history?",
    "História de TCE?": "History of head injury?",
    "História de aneurisma abdominal ou aórtico?": "History of abdominal or aortic aneurysm?",
    "História de convulsão?": "History of seizure?",
    "História de hematemeses?": "History of vomiting blood?",
    "História de perda de consciência?": "History of loss of consciousness?",
    "História de risco especial de infeção?": "History of special infection risk?",
    "História de sobredosagem ou envenenamento?": "History of overdose or poisoning?",
    "História de traumatismo torácico?": "History of chest trauma?",
    "História de traumatismo?": "History of trauma?",
    "História de viagens ao estrangeiro?": "History of foreign travel?",
    "História hematológica ou metabólica significativa?": "Significant haematological or metabolic history?",
    "História psiquiátrica significativa?": "Significant psychiatric history?",
    "História recente de viagem ao estrangeiro": "Recent history of foreign travel",
    "História significativa de alergia?": "Significant history of allergy?",
    "História significativa de doença respiratória?": "Significant history of respiratory disease?",
    "História significativa de hemorragia gastrointestinal?": "Significant history of gastrointestinal bleeding?",
    "Icterícia?": "Jaundice?",
    "Idade inferior a 16 anos?": "Under 16 years of age?",
    "Idade inferior a 25 anos?": "Under 25 years of age?",
    "Impossivel confirmar se vitima está em pé?": "Unable to confirm whether the person is standing?",
    "Impossivel confirmar se vitima fala?": "Unable to confirm whether the person is speaking?",
    "Inalação de fumo?": "Smoke inhalation?",
    "Incapacidade de andar?": "Unable to walk?",
    "Incapacidade de articular frases completas?": "Unable to speak in full sentences?",
    "Inconsolável pelos pais?": "Inconsolable by the parents?",
    "Infeção local?": "Local infection?",
    "Inflamação local?": "Local inflammation?",
    "Ingestão de objeto perigoso?": "Swallowed a dangerous object?",
    "Instalação súbita? (início < 12h)": "Sudden onset? (started <12h)",
    "Internamento compulsivo provável?": "Compulsory admission likely?",
    "Início agudo pós-traumático?": "Acute onset after injury?",
    "Início repentino?": "Sudden onset?",
    "Lesão elétrica?": "Electrical injury?",
    "Lesão ocular química?": "Chemical eye injury?",
    "Lesão por inalação?": "Inhalation injury?",
    "Massa abdominal visível?": "Visible abdominal mass?",
    "Mecanismo significativo de lesão / VTT": "Significant mechanism of injury / major trauma pathway?",
    "Mecanismo significativo de lesão?": "Significant mechanism of injury?",
    "Mortalidade moderada?": "Moderate mortality?",
    "Movimentos fetais reduzidos em gestação superior a 20 semanas?": "Reduced fetal movements in pregnancy over 20 weeks?",
    "Muito quente?": "Very hot (high temperature)?",
    "NEWS com um parâmetro de nivel 3?": "NEWS with a single level-3 parameter?",
    "NEWS de 5 a 6?": "NEWS score of 5 to 6?",
    "NEWS igual ou superior a 7?": "NEWS score of 7 or above?",
    "Novos sinais e/ou sintomas neurológicos?": "New neurological signs and/or symptoms?",
    "Novos sinais/sintomas de psicose?": "New signs/symptoms of psychosis?",
    "Novos sintomas de doença mental significativa?": "New symptoms of significant mental illness?",
    "Não reativo?": "Unresponsive?",
    "Não se alimenta?": "Not feeding?",
    "Não urina?": "Not passing urine?",
    "Olho vermelho?": "Red eye?",
    "Paragem cardiorespiratória / VVPCR": "Cardiac arrest / resuscitation pathway?",
    "Parto recente?": "Recent childbirth?",
    "Pedido de pilula do dia seguinte e sexo desprotegido 66/72 horas?": "Request for the morning-after pill with unprotected sex 66/72 hours ago?",
    "Pequena hemorragia incontrolável?": "Minor uncontrollable haemorrhage?",
    "Perda do controle da glicémia?": "Loss of blood-sugar control?",
    "Perda recente de audição?": "Recent hearing loss?",
    "Perda súbita de visão?": "Sudden loss of vision?",
    "Possivel paragem cardiorespiratória?": "Possible cardiac arrest?",
    "Possível gravidez?": "Possible pregnancy?",
    "Possível sépsis / VVS": "Possible sepsis / sepsis pathway?",
    "Possível sépsis?": "Possible sepsis?",
    "Preocupação com a salvaguarda do doente?": "Concern for the patient's safeguarding?",
    "Pressão arterial elevada?": "High blood pressure?",
    "Priapismo?": "Priapism?",
    "Problema recente?": "Recent problem?",
    "Profissional de saúde preocupado?": "Health professional concerned?",
    "Prolapso do cordão umbilical": "Umbilical cord prolapse",
    "Prostrado?": "Prostrate (extreme weakness)?",
    "Prurido moderado?": "Moderate itching?",
    "Prurido persistente?": "Persistent itching?",
    "Prurido severo?": "Severe itching?",
    "Quente?": "Hot (raised temperature)?",
    "Recente redução da acuidade visual?": "Recent reduction in visual acuity?",
    "Respiração ineficaz?": "Ineffective breathing?",
    "Risco de contaminação?": "Risk of contamination?",
    "Risco elevado de abandono sem avaliação?": "High risk of leaving before assessment?",
    "Risco elevado de agressão a terceiros?": "High risk of harm to others?",
    "Risco elevado de auto-agressão?": "High risk of self-harm?",
    "Risco moderado de abandono do local s/ avaliação?": "Moderate risk of leaving before assessment?",
    "Risco moderado de agressão a terceiros?": "Moderate risk of harm to others?",
    "Risco moderado de auto-agressão?": "Moderate risk of self-harm?",
    "Sem medicação disponível?": "No medication available?",
    "Sem reação ao estímulo dos pais?": "No response to the parents' stimulation?",
    "Sensação de corpo estranho?": "Foreign body sensation?",
    "Sinais de choque?": "Signs of shock?",
    "Sinais de desidratação?": "Signs of dehydration?",
    "Sinais de meningismo?": "Signs of meningism?",
    "Tensão cutânea?": "Skin tension?",
    "Tosse produtiva?": "Productive cough?",
    "Trabalho de parto?": "In labour?",
    "Transporte AEROMÉDICO nível B": "Aeromedical transport level B",
    "Transporte AEROMÉDICO nível C": "Aeromedical transport level C",
    "Transporte secundário NÍVEL A": "Secondary transport level A",
    "Transporte secundário NÍVEL B": "Secondary transport level B",
    "Transporte secundário NÍVEL C": "Secondary transport level C",
    "Trauma escrotal?": "Scrotal trauma?",
    "Traumatismo direto da região cervical?": "Direct trauma to the neck?",
    "Traumatismo direto da região lombar?": "Direct trauma to the lower back?",
    "Traumatismo ocular penetrante?": "Penetrating eye injury?",
    "Traumatismo vaginal?": "Vaginal trauma?",
    "Vertigem persistente de novo?": "New persistent vertigo?",
    "Vertigens?": "Vertigo (dizziness)?",
    "Vómitos incoercíveis?": "Uncontrollable vomiting?",
    "Vómitos persistentes?": "Persistent vomiting?",
}
