# -*- coding: utf-8 -*-
"""Nomes e descrições bilingues dos 56 fluxogramas de Manchester.

Chave = slug (id do fluxo). Valor = (nome_pt, nome_en, descricao_pt,
descricao_en, pediatrico). O nome é o título mostrado na lista de
queixas; a descrição é o subtítulo. 'pediatrico' marca os fluxos que a
tabela oficial identifica com "(P)".
"""

FLUXOS = {
    "agressao": (
        "Agressão",
        "Assault",
        "Foi vítima de uma agressão física.",
        "You have been physically assaulted.",
        False,
    ),
    "alergias": (
        "Alergias",
        "Allergy",
        "Reação alérgica, comichão ou inchaço.",
        "Allergic reaction, itching or swelling.",
        False,
    ),
    "asma": (
        "Asma",
        "Asthma",
        "Falta de ar ou pieira em pessoa com asma.",
        "Breathlessness or wheeze in someone with asthma.",
        False,
    ),
    "autoagressao": (
        "Autoagressão",
        "Self-harm",
        "Comportamento de autoagressão ou pensamentos de se magoar.",
        "Self-harm or thoughts of hurting yourself.",
        False,
    ),
    "bebe_que_chora_12_meses": (
        "Bebé que chora (< 12 meses)",
        "Crying baby (< 12 months)",
        "Bebé com menos de 12 meses que chora muito.",
        "A baby under 12 months who is crying a lot.",
        True,
    ),
    "cefaleia": ("Cefaleia", "Headache", "Dor de cabeça.", "Headache.", False),
    "comportamento_estranho": (
        "Comportamento estranho",
        "Unusual behaviour",
        "Mudança recente e estranha no comportamento.",
        "A recent, unusual change in behaviour.",
        False,
    ),
    "convulsoes": (
        "Convulsões",
        "Fits (seizures)",
        "Convulsão ou episódio semelhante.",
        "A seizure or a similar episode.",
        False,
    ),
    "corpo_estranho": (
        "Corpo estranho",
        "Foreign body",
        "Objeto preso ou engolido.",
        "An object stuck or swallowed.",
        False,
    ),
    "crianca_com_dificuldade_de_locomocao": (
        "Criança com dificuldade de locomoção",
        "Limping child",
        "Criança que coxeia ou não consegue andar bem.",
        "A child who is limping or cannot walk properly.",
        True,
    ),
    "crianca_que_nao_se_sente_bem": (
        "Criança que não se sente bem",
        "Unwell child",
        "Criança em mau estado geral, sem causa evidente.",
        "A child who is generally unwell, with no obvious cause.",
        True,
    ),
    "crianca_irritavel": (
        "Criança irritável",
        "Irritable child",
        "Criança irritável, difícil de acalmar.",
        "An irritable child who is hard to settle.",
        True,
    ),
    "diabetes": (
        "Diabetes",
        "Diabetes",
        "Problema relacionado com a diabetes ou o açúcar no sangue.",
        "A problem related to diabetes or blood sugar.",
        False,
    ),
    "diarreia_e_ou_vomitos": (
        "Diarreia e/ou vómitos",
        "Diarrhoea and/or vomiting",
        "Diarreia, vómitos ou ambos.",
        "Diarrhoea, vomiting or both.",
        False,
    ),
    "dispneia_no_adulto": (
        "Dispneia no adulto",
        "Shortness of breath in adults",
        "Falta de ar num adulto.",
        "Shortness of breath in an adult.",
        False,
    ),
    "dispneia_na_crianca": (
        "Dispneia na criança",
        "Shortness of breath in children",
        "Falta de ar numa criança.",
        "Shortness of breath in a child.",
        True,
    ),
    "doenca_mental": (
        "Doença mental",
        "Mental illness",
        "Agravamento de um problema de saúde mental.",
        "Worsening of a mental health problem.",
        False,
    ),
    "doencas_sexualmente_transmissiveis": (
        "Doenças sexualmente transmissíveis",
        "Sexually transmitted infections",
        "Sintomas de uma infeção sexualmente transmissível.",
        "Symptoms of a sexually transmitted infection.",
        False,
    ),
    "dor_abdominal_no_adulto": (
        "Dor abdominal no adulto",
        "Abdominal pain in adults",
        "Dor ou desconforto na barriga, num adulto.",
        "Tummy pain or discomfort in an adult.",
        False,
    ),
    "dor_abdominal_na_crianca": (
        "Dor abdominal na criança",
        "Abdominal pain in children",
        "Dor ou desconforto na barriga, numa criança.",
        "Tummy pain or discomfort in a child.",
        True,
    ),
    "dor_cervical": ("Dor cervical", "Neck pain", "Dor no pescoço.", "Pain in the neck.", False),
    "dor_de_garganta": (
        "Dor de garganta",
        "Sore throat",
        "Dor ou irritação na garganta.",
        "A painful or irritated throat.",
        False,
    ),
    "dor_lombar": (
        "Dor lombar",
        "Back pain",
        "Dor na parte de baixo das costas.",
        "Pain in the lower back.",
        False,
    ),
    "dor_testicular": (
        "Dor testicular",
        "Testicular pain",
        "Dor ou inchaço nos testículos.",
        "Pain or swelling in the testicles.",
        False,
    ),
    "dor_toracica": (
        "Dor torácica",
        "Chest pain",
        "Dor ou aperto no peito.",
        "Pain or tightness in the chest.",
        False,
    ),
    "embriaguez_aparente": (
        "Embriaguez aparente",
        "Apparently drunk",
        "Pessoa que aparenta estar embriagada.",
        "A person who appears to be intoxicated.",
        False,
    ),
    "erupcoes_cutaneas": (
        "Manchas, borbulhas ou erupção na pele",
        "Spots, bumps or a rash on the skin",
        "Erupções cutâneas.",
        "Rashes.",
        False,
    ),
    "estado_de_inconsciencia_sincope": (
        "Estado de inconsciência / síncope",
        "Unconsciousness / fainting",
        "Desmaio ou perda de consciência.",
        "Fainting or loss of consciousness.",
        False,
    ),
    "exposicao_a_quimicos": (
        "Exposição a químicos",
        "Exposure to chemicals",
        "Contacto com um produto químico perigoso.",
        "Contact with a hazardous chemical.",
        False,
    ),
    "feridas": (
        "Feridas",
        "Wounds",
        "Corte, ferida ou lesão da pele.",
        "A cut, wound or skin injury.",
        False,
    ),
    "grande_traumatismo": (
        "Acidente ou lesão grave",
        "A serious accident or injury",
        "Grande traumatismo.",
        "Major trauma.",
        False,
    ),
    "gravidez": (
        "Gravidez",
        "Pregnancy",
        "Problema durante a gravidez.",
        "A problem during pregnancy.",
        False,
    ),
    "hemorragia_gastrointestinal": (
        "Sangue nos vómitos ou nas fezes",
        "Blood in vomit or stools",
        "Hemorragia gastrointestinal.",
        "Gastrointestinal bleeding.",
        False,
    ),
    "hemorragia_vaginal": (
        "Hemorragia vaginal",
        "Vaginal bleeding",
        "Perda de sangue vaginal fora do normal.",
        "Abnormal vaginal bleeding.",
        False,
    ),
    "indisposicao_no_adulto": (
        "Indisposição no adulto",
        "Unwell adult",
        "Mal-estar geral num adulto, sem causa clara.",
        "A general feeling of being unwell in an adult, with no clear cause.",
        False,
    ),
    "infeccoes_locais_e_abcessos": (
        "Infeções locais e abcessos",
        "Local infections and abscesses",
        "Infeção ou abcesso numa zona do corpo.",
        "An infection or abscess in one area of the body.",
        False,
    ),
    "lesao_toraco_abdominal": (
        "Lesão toraco-abdominal",
        "Thoraco-abdominal injury",
        "Lesão no peito ou na barriga.",
        "An injury to the chest or abdomen.",
        False,
    ),
    "mordeduras_e_picadas": (
        "Mordeduras e picadas",
        "Bites and stings",
        "Mordedura de animal ou picada.",
        "An animal bite or a sting.",
        False,
    ),
    "pais_preocupados": (
        "Pais preocupados",
        "Worried parent",
        "Pais preocupados com uma criança.",
        "A parent worried about a child.",
        True,
    ),
    "palpitacoes": (
        "Sensação de batimentos cardíacos rápidos ou irregulares",
        "A feeling of fast or irregular heartbeats",
        "Palpitações.",
        "Palpitations.",
        False,
    ),
    "problemas_estomatologicos": (
        "Problemas estomatológicos",
        "Dental problems",
        "Problema nos dentes ou na boca.",
        "A problem with the teeth or mouth.",
        False,
    ),
    "problemas_faciais": (
        "Problemas faciais",
        "Facial problems",
        "Problema na face ou no rosto.",
        "A problem affecting the face.",
        False,
    ),
    "problemas_nos_membros": (
        "Problemas nos membros",
        "Limb problems",
        "Problema num braço ou numa perna.",
        "A problem with an arm or a leg.",
        False,
    ),
    "problemas_oftalmologicos": (
        "Problema nos olhos ou na visão",
        "A problem with the eyes or vision",
        "Problemas oftalmológicos.",
        "Eye problems.",
        False,
    ),
    "problemas_de_ouvidos": (
        "Problemas de ouvidos",
        "Ear problems",
        "Dor ou problema nos ouvidos.",
        "Ear pain or an ear problem.",
        False,
    ),
    "problemas_urinarios": (
        "Problemas urinários",
        "Urinary problems",
        "Dificuldade ou dor ao urinar.",
        "Difficulty or pain passing urine.",
        False,
    ),
    "queda": ("Queda", "Falls", "Queda recente.", "A recent fall.", False),
    "queimaduras_profundas_e_superficiais": (
        "Queimaduras profundas e superficiais",
        "Burns and scalds",
        "Queimadura na pele.",
        "A burn to the skin.",
        False,
    ),
    "sobredosagem_e_envenenamento": (
        "Sobredosagem e envenenamento",
        "Overdose and poisoning",
        "Ingestão de excesso de medicação ou de uma substância tóxica.",
        "Taking too much medication or a poisonous substance.",
        False,
    ),
    "t_c_e_trauma_cranio_encefalico": (
        "Pancada ou traumatismo na cabeça",
        "A blow or injury to the head",
        "T.C.E. – Trauma crânio-encefálico.",
        "Head injury.",
        False,
    ),
    "rn_que_nao_esta_bem_28_dias": (
        "Recém-nascido que não está bem (< 28 dias)",
        "Unwell newborn (< 28 days)",
        "Recém-nascido com menos de 28 dias em mau estado.",
        "A newborn under 28 days who is unwell.",
        True,
    ),
    "bebe_que_nao_esta_bem_12_meses": (
        "Bebé que não está bem (< 12 meses)",
        "Unwell baby (< 12 months)",
        "Bebé com menos de 12 meses em mau estado.",
        "A baby under 12 months who is unwell.",
        True,
    ),
    "infecoes_emergentes": (
        "Infeções emergentes",
        "Emerging infections",
        "Suspeita de infeção emergente ou de risco de saúde pública.",
        "Suspected emerging infection or public-health risk.",
        False,
    ),
    "pedido_de_apoio_diferenciado": (
        "Pedido de apoio diferenciado",
        "Request for differentiated support",
        "Pedido de apoio ou transporte diferenciado entre unidades.",
        "Request for differentiated support or transfer between units.",
        False,
    ),
    "pedido_de_medicacao": (
        "Pedido de medicação",
        "Request for medication",
        "Pedido relacionado com medicação.",
        "A request related to medication.",
        False,
    ),
    "pedido_para_terceiros": (
        "Pedido para terceiros",
        "Request on behalf of another",
        "Pedido feito em nome de outra pessoa.",
        "A request made on behalf of another person.",
        False,
    ),
}
